import { A } from '@pounce'
import { Code, Section } from '../../components'

const installFrontend = `pnpm add @pounce/core @pounce/kit @pounce/ui @pounce/adapter-pico @picocss/pico mutts
pnpm add -D vite typescript sass

# Add @pounce/board when you want the back-end/full-stack layer.`

const viteConfig = `import { defineConfig } from 'vite'
import { pounceBarrelPlugin, pounceMinimalPackage } from '@pounce/core/plugin'

export default defineConfig({
  plugins: [
    ...pounceMinimalPackage(),
    pounceBarrelPlugin({
      name: '@pounce',
      skeleton: 'front-end',
      adapter: '@pounce/adapter-pico',
    }),
  ],
})`

const barrelShapes = `// Think: kit / FE / BE / F-S
// Actual plugin values are: 'kit' | 'front-end' | 'back-end' | 'full-stack'

pounceBarrelPlugin({ name: '@pounce', skeleton: 'kit' })
pounceBarrelPlugin({ name: '@pounce', skeleton: 'front-end', adapter: '@pounce/adapter-pico' })
pounceBarrelPlugin({ name: '@pounce', skeleton: 'back-end' })
pounceBarrelPlugin({ name: '@pounce', skeleton: 'full-stack', adapter: '@pounce/adapter-pico' })`

const tsconfig = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "react",
    "jsxFactory": "h",
    "jsxFragmentFactory": "Fragment",
    "strict": true,
    "skipLibCheck": true,
    "paths": {
      "@pounce": ["./.generated-types/@pounce.d.ts"]
    }
  },
  "include": ["src/**/*", ".generated-types/**/*.d.ts"]
}`

const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>My Pounce App</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css" />
</head>
<body>
  <div id="app"></div>
  <script type="module" src="/src/main.tsx"></script>
</body>
</html>`
const mainTsx = `import { latch } from '@pounce'

function App() {
  return (
    <main class="container">
      <h1>Hello Pounce!</h1>
      <p>Your first pounce application is running.</p>
    </main>
  )
}

latch('#app', <App />)`

export default function GettingStartedPage() {
	return (
		<article>
			<h1>Getting Started</h1>
			<p>
				Pounce works best when you read it as <strong>logical/assertive programming for UI</strong>:
				you state relationships once, and the runtime keeps the concrete DOM and app state aligned.
			</p>
			<p class="docs-subtitle">
				This page is the map before the first app: how <code>@pounce/core</code>,{' '}
				<code>@pounce/kit</code>,<code>@pounce/ui</code>, adapters, and <code>@pounce/board</code>{' '}
				fit together, and how the Vite plugin can generate a virtual <code>@pounce</code> barrel
				with the union of the exports you choose.
			</p>

			<Section title="Package Map" id="package-map">
				<p>
					The Pounce suite starts at <code>@pounce/core</code>, then adds platform services through{' '}
					<code>@pounce/kit</code>, then either UI/adapters, full-stack routing, or both.
				</p>
				<p>
					Under the hood, Pounce relies on <a href="https://www.npmjs.com/package/mutts">mutts</a>{' '}
					for reactive primitives, but
					<code>mutts</code> is an external foundation rather than a package in the suite.
				</p>
				<div class="docs-map">
					<div class="docs-map-row">
						<A href="/core" class="docs-map-node">
							<code>@pounce/core</code>
							<small>JSX, env, directives, reconciler</small>
						</A>
						<span class="docs-map-arrow">→</span>
						<A href="/kit" class="docs-map-node">
							<code>@pounce/kit</code>
							<small>router, client, storage, intl, api</small>
						</A>
					</div>
					<div class="docs-map-row">
						<A href="/ui" class="docs-map-node">
							<code>@pounce/ui</code>
							<small>headless models and directives</small>
						</A>
						<span class="docs-map-arrow">→</span>
						<A href="/adapters/pico" class="docs-map-node">
							<code>@pounce/adapter-pico</code>
							<small>actual styled components</small>
						</A>
						<span class="docs-map-arrow">or</span>
						<A href="/board" class="docs-map-node">
							<code>@pounce/board</code>
							<small>SSR, routes, middleware, server hooks</small>
						</A>
					</div>
					<div class="docs-map-row">
						<div class="docs-map-node docs-map-node-barrel">
							<code>@pounce</code>
							<small>virtual package union generated by the Vite plugin</small>
						</div>
					</div>
				</div>
				<div class="docs-jump-grid">
					<a href="#barrel-shapes">Barrel shapes</a>
					<a href="#installation">Installation</a>
					<a href="#vite-configuration">Vite configuration</a>
					<a href="#typescript-configuration">TypeScript configuration</a>
					<a href="#html-entry-point">HTML entry point</a>
					<a href="#your-first-component">Your first component</a>
					<a href="#next-steps">Next steps</a>
				</div>
			</Section>

			<Section title="Barrel Shapes" id="barrel-shapes">
				<p>
					Think of the choices as <code>kit</code> / FE / BE / F-S. The actual plugin values are
					<code>'kit'</code>, <code>'front-end'</code>, <code>'back-end'</code>, and{' '}
					<code>'full-stack'</code>.
				</p>
				<p>
					There is no package-to-package re-exporting in the suite. Instead,
					<code>pounceBarrelPlugin()</code> generates a virtual module named <code>@pounce</code>
					whose exports are the union of the selected packages.
				</p>
				<table>
					<thead>
						<tr>
							<th>Skeleton</th>
							<th>
								Virtual <code>@pounce</code> contents
							</th>
							<th>Use when</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<code>kit</code>
							</td>
							<td>
								<code>@pounce/core</code> + <code>@pounce/kit</code>
							</td>
							<td>Shared browser/runtime services without the headless UI or board layers.</td>
						</tr>
						<tr>
							<td>
								<code>front-end</code>
							</td>
							<td>
								<code>@pounce/core</code> + <code>@pounce/kit</code> + <code>@pounce/ui</code> +
								adapter
							</td>
							<td>
								Client-side app with headless UI and a presentation adapter such as{' '}
								<A href="/adapters/pico">
									<code>@pounce/adapter-pico</code>
								</A>
								.
							</td>
						</tr>
						<tr>
							<td>
								<code>back-end</code>
							</td>
							<td>
								<code>@pounce/core</code> + <code>@pounce/kit</code> + <code>@pounce/board</code>
							</td>
							<td>Routing, SSR, middleware, and server work without the UI/adapters layer.</td>
						</tr>
						<tr>
							<td>
								<code>full-stack</code>
							</td>
							<td>
								<code>@pounce/core</code> + <code>@pounce/kit</code> + <code>@pounce/ui</code> +
								adapter + <code>@pounce/board</code>
							</td>
							<td>The full Pounce stack behind one barrel.</td>
						</tr>
					</tbody>
				</table>
				<Code code={barrelShapes} lang="typescript" />
			</Section>

			<Section title="Installation" id="installation">
				<p>
					For a first browser app, install the front-end stack. Add <code>@pounce/board</code> only
					when you want the back-end/full-stack layer.
				</p>
				<Code code={installFrontend} lang="bash" />
			</Section>

			<Section title="Vite Configuration" id="vite-configuration">
				<p>
					Use the minimal Pounce JSX transform and generate a front-end virtual <code>@pounce</code>
					package that unions the exports from Core, Kit, UI, and your chosen adapter.
				</p>
				<Code code={viteConfig} lang="typescript" />
			</Section>

			<Section title="TypeScript Configuration" id="typescript-configuration">
				<Code code={tsconfig} lang="json" />
			</Section>

			<Section title="HTML Entry Point" id="html-entry-point">
				<Code code={indexHtml} lang="html" />
			</Section>

			<Section title="Your First Component" id="your-first-component">
				<p>
					Create <code>src/main.tsx</code>:
				</p>
				<Code code={mainTsx} lang="tsx" />
				<p>
					Run <code>pnpm vite</code> and open the browser.
				</p>
			</Section>

			<Section title="Next Steps" id="next-steps">
				<ul>
					<li>
						<A href="/getting-started/concepts">Core Concepts</A> — env, reactivity, components,
						directives
					</li>
					<li>
						<A href="/core">@pounce/core</A> — JSX factory, PounceElement, reconciler
					</li>
					<li>
						<A href="/kit">@pounce/kit</A> — router, client state, storage, and integration services
					</li>
					<li>
						<A href="/ui">@pounce/ui</A> — headless primitives, directives, overlays, and models
					</li>
					<li>
						<A href="/board">@pounce/board</A> — when you want file-based routing and SSR
					</li>
				</ul>
			</Section>
		</article>
	)
}
