import { Code, PackageHeader, Section } from '../../components'

const adapterSetup = `import { pounceBarrelPlugin, pounceMinimalPackage } from '@pounce/core/plugin'

export default defineConfig({
  plugins: [
    ...pounceMinimalPackage(),
    pounceBarrelPlugin({
      skeleton: 'front-end',
      adapter: '@pounce/adapter-pico',
    }),
  ],
})

import '@picocss/pico/css/pico.min.css'
import '@pounce/adapter-pico/css'`

const buttonExample = `import { Button } from '@pounce'

// Headless behavior comes from @pounce/ui models.
// The visual implementation comes from your adapter.
<Button variant="primary">Save</Button>
<Button variant="danger">Delete</Button>
<Button variant="success">Confirm</Button>

// Dot-syntax is generated by uiComponent(...)
<Button.primary>Save</Button.primary>

// Loading state via directive:
<Button use:loading={state.saving}>Submitting...</Button>

// With icons (via pure-glyf):
<Button icon="check">Save</Button>`

const overlayExample = `import { StandardOverlays } from '@pounce'

// Wrap your app with StandardOverlays:
<StandardOverlays>
  <App />
</StandardOverlays>

// Then use env.dialog / env.toast / env.drawer:
env.toast.success('Saved!')
env.toast.error('Something went wrong')

env.dialog({ title: 'Confirm', message: 'Are you sure?' })

env.drawer({ children: <SettingsPanel />, side: 'right' })`

const displayContext = `import { DisplayProvider, ThemeToggle, useDisplayContext } from '@pounce'
import { reactive } from 'mutts'

const settings = reactive({ theme: 'auto' as const })

function ThemeLabel(_props: {}, env: Env) {
  const dc = useDisplayContext(env)
  return <span>Resolved theme: {dc.theme}</span>
}

function App() {
  return (
    <DisplayProvider theme={settings.theme}>
      <ThemeToggle settings={settings} />
      <ThemeLabel />
    </DisplayProvider>
  )
}`

export default function UIPage() {
	return (
		<article>
			<PackageHeader
				name="@pounce/ui"
				description="Headless primitives, directives, overlays, and models for adapter-driven Pounce UIs."
			/>

			<p>
				<code>@pounce/ui</code> is the headless layer of the Pounce UI stack. It exports models,
				directives, overlays, and shared utilities; visual components come from an adapter such as{' '}
				<code>@pounce/adapter-pico</code> and are typically consumed through the{' '}
				<code>@pounce</code> front-end barrel.
			</p>

			<Section title="Adapter Setup">
				<p>
					Use a front-end barrel so your app imports from one place while the adapter decides the
					actual component implementation.
				</p>
				<Code code={adapterSetup} lang="tsx" />
			</Section>

			<Section title="Components">
				<p>Available components:</p>
				<table>
					<thead>
						<tr>
							<th>Component</th>
							<th>Description</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<code>Button</code>
							</td>
							<td>Interactive button with variants, icons, loading state</td>
						</tr>
						<tr>
							<td>
								<code>ButtonGroup</code>
							</td>
							<td>Group buttons with shared styling</td>
						</tr>
						<tr>
							<td>
								<code>Accordion</code>
							</td>
							<td>Collapsible content section</td>
						</tr>
						<tr>
							<td>
								<code>Card</code>
							</td>
							<td>Content container with header/footer slots</td>
						</tr>
						<tr>
							<td>
								<code>Menu</code>
							</td>
							<td>Navigation menu with keyboard support</td>
						</tr>
						<tr>
							<td>
								<code>Dialog</code>
							</td>
							<td>Modal dialog with backdrop and focus trap</td>
						</tr>
						<tr>
							<td>
								<code>Toast</code>
							</td>
							<td>Notification toasts with variants</td>
						</tr>
						<tr>
							<td>
								<code>Drawer</code>
							</td>
							<td>Slide-out panel (left/right)</td>
						</tr>
						<tr>
							<td>
								<code>Progress</code>
							</td>
							<td>Progress bar with indeterminate mode</td>
						</tr>
						<tr>
							<td>
								<code>InfiniteScroll</code>
							</td>
							<td>Virtualized list with variable height</td>
						</tr>
						<tr>
							<td>
								<code>Toolbar</code>
							</td>
							<td>Horizontal toolbar with spacer</td>
						</tr>
						<tr>
							<td>
								<code>Stars</code>
							</td>
							<td>Star rating input with single or range selection</td>
						</tr>
						<tr>
							<td>
								<code>Badge</code>
							</td>
							<td>Small uppercase status label</td>
						</tr>
						<tr>
							<td>
								<code>Pill</code>
							</td>
							<td>Medium status indicator with icons</td>
						</tr>
						<tr>
							<td>
								<code>Chip</code>
							</td>
							<td>Interactive dismissible token</td>
						</tr>
						<tr>
							<td>
								<code>CheckButton</code>
							</td>
							<td>Toggle button with role="checkbox" semantics</td>
						</tr>
						<tr>
							<td>
								<code>RadioButton</code>
							</td>
							<td>Button-style radio with group/value binding</td>
						</tr>
						<tr>
							<td>
								<code>Multiselect</code>
							</td>
							<td>Dropdown multi-selection with Set binding</td>
						</tr>
						<tr>
							<td>
								<code>Heading</code>
							</td>
							<td>Semantic heading (h1–h6) with variant coloring</td>
						</tr>
						<tr>
							<td>
								<code>Text</code>
							</td>
							<td>Paragraph text with size presets and muted mode</td>
						</tr>
						<tr>
							<td>
								<code>Link</code>
							</td>
							<td>Styled anchor with client-side routing</td>
						</tr>
						<tr>
							<td>
								<code>Icon</code>
							</td>
							<td>Icon rendering via adapter factory</td>
						</tr>
						<tr>
							<td>
								<code>Forms</code>
							</td>
							<td>Select, Combobox, Checkbox, Radio, Switch</td>
						</tr>
						<tr>
							<td>
								<code>Layout</code>
							</td>
							<td>Stack, Inline, Grid, AppShell, Container</td>
						</tr>
					</tbody>
				</table>
			</Section>

			<Section title="Buttons">
				<Code code={buttonExample} lang="tsx" />
			</Section>

			<Section title="Overlay System">
				<p>
					Dialogs, toasts, and drawers use a shared overlay system. Inject{' '}
					<code>StandardOverlays</code> near the app root to enable <code>env.dialog</code>,{' '}
					<code>env.toast</code>, and <code>env.drawer</code>.
				</p>
				<Code code={overlayExample} lang="tsx" />
			</Section>

			<Section title="Display Context">
				<p>
					<code>DisplayProvider</code> resolves theme, direction, locale, and timezone for its
					subtree. <code>ThemeToggle</code> mutates your reactive settings object, while{' '}
					<code>useDisplayContext()</code> reads the resolved values from env.
				</p>
				<Code code={displayContext} lang="tsx" />
			</Section>

			<Section title="Directives">
				<p>UI directives for common patterns:</p>
				<ul>
					<li>
						<code>use:badge</code> — badge overlay on any element
					</li>
					<li>
						<code>use:intersect</code> — intersection observer
					</li>
					<li>
						<code>use:loading</code> — loading state with spinner
					</li>
					<li>
						<code>use:pointer</code> — pointer event tracking
					</li>
					<li>
						<code>use:resize</code> — resize observer
					</li>
					<li>
						<code>use:scroll</code> — scroll position tracking
					</li>
				</ul>
			</Section>
		</article>
	)
}
